number1 = int(input("Enter the number 1"))
number2 = int(input("Enter the number 2"))
number3 = int(input("Enter the number 3"))
number4 = int(input("Enter the number 4"))
number5 = int(input("Enter the number 5"))
number6 = int(input("Enter the number 6"))
number7 = int(input("Enter the number 7"))
number8 = int(input("Enter the number 8"))
a=set(number1, number2, number3, number4, number5, number6, number6, number7, number8)
# a.add(number1)
# a.add(number2)
# a.add(number3)
# a.add(number4)
# a.add(number5)
# a.add(number6)
# a.add(number7)
# a.add(number8)
print(a)